const municipios = [
    "Guatapé", 
    "Medellín", 
    "Santa Fe de Antioquia", 
    "Jardín", 
    "Rionegro", 
    "Belmira",
    "San Rafael",
    "San Carlos",
    "Santa Elena",
    "San Jerónimo",
    "Turbo",
    "Necoclí",
    "La Ceja",
    "La Unión",
    "El Carmen de Viboral",
    "Sabaneta",
    "Envigado",
    "Itagüí",
    "Bello",
    "Barbosa",
    "El Retiro",
    "Copacabana",
    "Girardota",
    "Yarumal",
    "Amagá",
];

export default municipios;