const paquetesTuristicos = [
    {
      id: 1,
      titulo: "Aventura en la Montaña",
      descripcion: "Explora senderos naturales con guías expertos.",
      imagen: "/images/imagen_1.png",
      precio: "150 USD",
      categoria: "Experiencias",
      municipio: "La Ceja",
    },
    {
      id: 2,
      titulo: "Tour Gastronómico",
      descripcion: "Descubre la comida típica de la región.",
      imagen: "images/imagen_2.jpg",
      precio: "80 USD",
      categoria: "Experiencias",
      municipio: "Necoclí",
    },
    {
        id: 3,
        titulo: "Paseo en Lancha",
        descripcion: "Recorre ríos y lagos en un ambiente natural.",
        imagen: "images/imagen_3.jpg",
        precio: "120 USD",
        categoria: "Transporte",
        municipio: "San Carlos",
      },
      {
        id: 4,
        titulo: "Alojamiento Rural",
        descripcion: "Descansa en cabañas rústicas en medio de la naturaleza.",
        imagen: "images/imagen_4.png",
        precio: "200 USD",
        categoria: "Alojamiento",
        municipio: "Santa Fe de Antioquia",
      },
      {
        id: 5,
        titulo: "Tour Histórico",
        descripcion: "Conoce la historia de la región con guías especializados.",
        imagen: "images/Parque-de-Itagui.jpg",
        precio: "100 USD",
        categoria: "Experiencias",
        municipio: "Itagui",
      },
      {
        id: 6,
        titulo: "Tour de Centros Históricos",
        descripcion: "Visita los centros históricos de la región.",
        imagen: "images/imagen_6.jpg",
        precio: "50 USD",
        categoria: "Experiencias",
        municipio: "Medellín",
      },
        {
            id: 7,
            titulo: "Tour de Compras",
            descripcion: "Recorre los mejores centros comerciales de la región.",
            imagen: "images/imagen_7.jpg",
            precio: "70 USD",
            categoria: "Paquetes completos",
            municipio: "Rionegro",
        },
        {
            id: 8,
            titulo: "Tour de Bicicleta",
            descripcion: "Recorre senderos naturales en bicicleta.",
            imagen: "images/imagen_8.jpg",
            precio: "40 USD",
            categoria: "Experiencias",
            municipio: "Envigado",
        },
        {
            id: 9,
            titulo: "Tour de Museos",
            descripcion: "Visita los mejores museos de la región.",
            imagen: "images/imagen_9.jpg",
            precio: "60 USD",
            categoria: "Alojamiento",
            municipio: "Bello",
        },
        {
            id: 10,
            titulo: "Tour de Parques",
            descripcion: "Recorre los parques más emblemáticos de la región.",
            imagen: "images/imagen_10.jpg",
            precio: "50 USD",
            categoria: "Transporte",
            municipio: "Medellín",
        },
        {
            id: 11,
            titulo: "Tour de Cafeterías",
            descripcion: "Visita las mejores cafeterías de la región.",
            imagen: "images/imagen_11.jpg",
            precio: "30 USD",
            categoria: "Alojamiento",
            municipio: "Sabaneta",
        },
        {
            id: 12,
            titulo: "Tour de Parques Temáticos",
            descripcion: "Recorre los parques temáticos de la región.",
            imagen: "images/imagen_12.jpg",
            precio: "80 USD",
            categoria: "Experiencias",
            municipio: "La Estrella",
        },
        {
            id: 13, 
            titulo: "Tour de Playas",
            descripcion: "Recorre las playas más hermosas de la región.",
            imagen: "images/imagen_13.jpg",
            precio: "100 USD",  
            categoria: "Transporte",
            municipio: "Turbo",
        },
        {
            id: 14,
            titulo: "Tour de Parques Naturales",    
            descripcion: "Recorre los parques naturales de la región.",
            imagen: "images/imagen_14.jpg",
            precio: "120 USD",
            categoria: "Paquetes completos",
            municipio: "Amagá",
        },
        {
            id: 15,
            titulo: "Aventura en la Montaña",
            descripcion: "Explora senderos naturales con guías expertos.",
            imagen: "images/imagen_15.jpg",
            precio: "150 USD",
            categoria: "Experiencias",
            municipio: "Guatapé",
        },
        {
            id: 16,
            titulo: "Paseo en Lancha",
            descripcion: "Recorre ríos y lagos en un ambiente natural.",
            imagen: "images/imagen_16.jpg",
            precio: "120 USD",
            categoria: "Transporte",
            municipio: "Guatapé",
        }

  ];
  
  export default paquetesTuristicos;